name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0

      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build

      - name: Checkout destination branch
        uses: actions/checkout@v2
        with:
          ref: build
          path: build

      - name: Copy
        run: |
          cd build
          git rm -rf .
          cp -r ../* .

      - name: Commit & push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update from ${{ github.ref }}"
          git push
